# Copied from https://github.com/urbangrammarai/data_processing/blob/master/.github/workflows/build_book.yml
name: Build Jupyter book
on:
  push:
    branches:
      - master
jobs:
  build-html-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-activate-base: false
          python-version: '3.10'
          environment-file: ci/build-website.yaml
          activate-environment: build-website

      - name: Build HTML
        shell: bash -l {0}
        continue-on-error: false
        run: |
          make html
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "GA build of book HTML" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
